name: portel.nexgensis.com

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write
  pull-requests: read
  issues: read 

jobs:
  backend:
    name: Backend
    uses: Nexgensis/github-actions/.github/workflows/docker-image-build.yml@main
    with:
      image_name: webmanager-backend
      context: .
      dockerfile: Dockerfile.Backend
      branch: main
      environment: Staging

  frontend:
    name: Frontend
    uses: Nexgensis/github-actions/.github/workflows/docker-image-build.yml@main
    with:
      image_name: webmanager-frontend
      context: .
      dockerfile: Dockerfile.Frontend
      branch: main
      environment: Staging

  deploy:
    name: Deploy
    needs: [backend, frontend]
    uses: Nexgensis/github-actions/.github/workflows/deploy.yml@main
    with:
      cd_path: /root/webmanager
      image_backend: webmanager-backend
      image_frontend_1: webmanager-frontend
      other_container: webmanager
      frontend_port: "10000"
      environment: Staging
    secrets:
      host: ${{ secrets.DEMO_SERVER_IP }}
      ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      username: root

  cleanup-backend:
    needs: [deploy]
    uses: Nexgensis/github-actions/.github/workflows/cleanup-docker-images.yml@main
    with:
      image_name: ghcr.io/nexgensis/${{ github.event.inputs.project_name }}-backend
      environment: Staging
    secrets:
      host: ${{ secrets.DEMO_SERVER_IP }} 
      ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      username: root
  
  cleanup-frontend:
    needs: [deploy]
    uses: Nexgensis/github-actions/.github/workflows/cleanup-docker-images.yml@main
    with:
      image_name: ghcr.io/nexgensis/${{ github.event.inputs.project_name }}-frontend
      environment: Staging
    secrets:
      host: ${{ secrets.DEMO_SERVER_IP }} 
      ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      username: root

  release-notes:
    needs: [cleanup-backend, cleanup-frontend]
    uses: Nexgensis/github-actions/.github/workflows/release-notes.yml@main
  
  # release-email:
  #   needs: release-notes
  #   uses: Nexgensis/github-actions/.github/workflows/release-email.yml@main
  #   with:
  #     tag: ${{ needs.release-notes.outputs.tag }}
  #     environment: Staging
  #   secrets:
  #     EMAIL_USER: ${{ secrets.EMAIL_USER }}
  #     EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
